server:
  port: 9041
spring:
  application:
    name: cloud-provider
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:9010/eureka/
security:
  oauth2:
    resource:
      id: cloud-provider1
      user-info-uri: http://localhost:9060/user
      prefer-token-info: false